<?php
require_once('../Foundation/Utility/USingleton.php');
require_once('../Foundation/Fdb.php');
require_once('../Foundation/FRaccoglitore_cartelle.php');
require_once('../Foundation/FImmagine.php');
require_once('../Foundation/FUtente.php');
require_once('../Foundation/FCartella.php');
require_once('../Foundation/FNota.php');
require_once('../Entity/EUtente.php');
require_once('../Entity/EImmagine.php');
require_once('../Entity/ECartella.php');
require_once('../Entity/ENota.php');
require_once('../Entity/ENotaCondivisa.php');
require_once('../Entity/EPromemoria.php');
require_once('../Entity/EPromemoriaCondiviso.php');
$fdb = USingleton::getInstance('Fdb');
$futente = USingleton::getInstance('FUtente');
$fcartella = USingleton::getInstance('FCartella');
$fraccoglitore_cartelle = USingleton::getInstance('FRaccoglitore_cartelle');
$fnota = USingleton::getInstance('FNota');
$path="../Foundation/Utility/utenteDefault.png";
$image = new EImmagine(basename($path), filesize($path), "image/png", $path);
$fimmagine=USingleton::getInstance('FImmagine');
//$fimmagine->inserisciImmagine($image);
$utente = new EUtente("ciaociaociao", "ciao2fgdgfd", "fabio", "di sabatino", $image, "fabio.disaba@gmail.com", "attivato", "normale");
$utente->setCodiceAttivazione();
$futente->inserisciUtente($utente);
$risultato = $futente->getUtenteByEmail($utente->getEmail());
$cartella = new ECartella("Ciao", 0, "#FFFFFF");
//$fcartella->inserisciCartella($cartella,"privata",$utente->getEmail());
$ris = $fcartella->getCartellaById(181);
$dati = array("id_cartella" => 181,"email_utente" => $utente->getEmail(),"posizione" => 0);
$fraccoglitore_cartelle->aggiungiAlRaccoglitoreCartelle($dati);
$risultato1 = $fraccoglitore_cartelle->getCartelleByUtente('emanuele.fianco@gmail.com',2,0);
$risultato2 = $fraccoglitore_cartelle->getMaxPosizioneCartellaByUtente('emanuele.fianco@gmail.com');
$nota = new ENota("1 nota", "qualcosa", 0, "#FFFFFF");
//$fnota->inserisciNota($nota,$utente->getEmail());
$notacondivisa = new ENotaCondivisa("1 nota", "qualcosa", 0, "#FFFFFF", $utente->getEmail());
//$fnota->inserisciNota($notacondivisa,$utente->getEmail());
$format = 'Y-m-d H:i:s';
$date = DateTime::createFromFormat($format,'2009-02-15 15:16:17');
$promemoria = new EPromemoria("1 nota", "qualcosa", 0, "#FFFFFF", $date);
//$fnota->inserisciNota($promemoria,$utente->getEmail());
$promemoriacondiviso = new EPromemoriaCondiviso("1 nota", "qualcosa", 0, "#FFFFFF", $utente->getEmail(), $date);
//$fnota->inserisciNota($promemoriacondiviso,$utente->getEmail());
//$return = $fdb->getDb()->lastInsertId();
//var_dump($return);
?>