<?php
require_once('../Entity/ECartella.php');
require_once('../Entity/ENota.php');
require_once('../Entity/ENotaCondivisa.php');
require_once('../Entity/EPartecipante.php');
require_once('../Entity/EPromemoria.php');
require_once('../Entity/EUtente.php');
require_once("../Foundation/Fdb.php");
require_once("../Foundation/FUtente.php");
require_once("../Foundation/FCartella.php");
require_once("../Foundation/FNota.php");
require_once("../Foundation/FPartecipante.php");
require_once("../Foundation/FPartecipano.php");
require_once("../Foundation/FCondividono.php");
require_once("../Foundation/Utility/USingleton.php");
$db=USingleton::getInstance('Fdb');
$futente=USingleton::getInstance('FUtente');
$fcartella=USingleton::getInstance('FCartella');
$fnota=USingleton::getInstance('FNota');
$fpartecipante=USingleton::getInstance('FPartecipante');
$fpartecipano=USingleton::getInstance('FPartecipano');
$fcondividono=USingleton::getInstance('FCondividono');
$idcart=$fcartella->getCartelleByUtente('emanuele.fianco@gmail.com');
$idcart=$idcart[0]['id'];
$note = $fnota->getNoteByCartella($idcart);
$part=new EPartecipante('emanuefff', 'gggg', 'emanuele.fianco@gmail.com', 'admin');
$fpartecipante->inserisciPartecipante($part);
$p['id_cartella']= $idcart;
$p['email_partecipante']= 'emanuele.fianco@gmail.com';
$fpartecipano->aggiungiAlGruppo($p);
$co=$fnota->getNoteByCartella($idcart);
$co=$co[0]['id'];
$con['id_nota']=$co;
$con['email_partecipante']='emanuele.fianco@gmail.com';
$fcondividono->AggiungiAllaCondivisione($con);
$ris=$fpartecipante->getPartecipantiByIdCartella($idcart);
$ris1=$fpartecipante->getPartecipantiByIdNota($co);
$cose_da_cambiare= array('posizione' => 10,
						 'id' => $idcart);
$righeToccate=$fcartella->updateCartella($cose_da_cambiare);
echo json_encode($note);
?>